# Generated by Django 2.2 on 2019-04-15 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("test_project", "0005_auto_20190415_1952")]

    operations = [
        migrations.CreateModel(
            name="SingleChildToy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="toy",
                        to="test_project.DeeplyNestedChild",
                    ),
                ),
            ],
        )
    ]
