# Generated by Django 2.2 on 2019-04-15 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("test_project", "0008_auto_20190415_2003")]

    operations = [
        migrations.AlterField(
            model_name="deeplynestedchild",
            name="parent",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child",
                to="test_project.DeeplyNestedParent",
            ),
        )
    ]
