# Generated by Django 2.2.1 on 2019-09-05 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0009_auto_20190415_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrandKidFavouriteMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GrandKidFavouriteToy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toy', to='test_project.GrandKids')),
            ],
        ),
        migrations.AddField(
            model_name='grandkids',
            name='favourite_meal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='eaters', to='test_project.GrandKidFavouriteMeal'),
            preserve_default=False,
        ),
    ]
