# Generated by Django 3.0.7 on 2020-12-21 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0009_auto_20190415_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childb',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_b', to='test_project.TopLevel'),
        ),
    ]
