# Generated by Django 2.2.1 on 2019-09-05 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0010_auto_20190905_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grandkids',
            name='favourite_meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eaters', to='test_project.GrandKidFavouriteMeal'),
        ),
    ]
