# Generated by Django 2.2.1 on 2019-09-05 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0011_auto_20190905_0841'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TopLevel',
            new_name='Parent',
        ),
        migrations.RenameField(
            model_name='childa',
            old_name='childA_text',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='childabro',
            old_name='brother_text',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='childb',
            old_name='childB_text',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='top_level_text',
            new_name='name',
        ),
    ]
